// ESLint flat config for JellyQuest.
//
// This repo deliberately contains TWO different JavaScript dialects, and
// the whole point of this file is to keep them apart:
//
//   * src/overlay/**, tizen.js and dev/fixtures/** are hand-written ES5
//     (var, IIFEs, no modules, no arrow functions). That is NOT legacy
//     sloppiness -- the hardware floor is Tizen 4.6, whose Chromium is
//     roughly M56-M63, and scripts/build-overlay.mjs concatenates these
//     files into a single classic <script> because native ES modules
//     only landed in Chromium 61. These are linted with ecmaVersion 5 so
//     that accidentally typing `const`/`=>` fails the gate instead of
//     shipping a bundle the oldest TVs cannot parse.
//
//   * scripts/**.mjs, test/**.mjs and gulpfile.babel.js are modern Node
//     ESM and only ever run on the build machine, so they get the
//     current ecmaVersion and node globals.
//
// Rule selection is deliberately bug-focused (undefined variables,
// unused variables, unreachable code, accidental globals) rather than
// stylistic -- this gate exists to catch mistakes, not to churn source.
import js from '@eslint/js';
import globals from 'globals';

// Globals the overlay bundle publishes onto `window` and then reads back
// from sibling files. build-overlay.mjs concatenates the files in a
// fixed order, so these really are cross-file globals by design; without
// declaring them here every module would trip no-undef on its siblings.
const overlayGlobals = {
    JellyQuestCards: 'writable',
    JellyQuestDetailScreen: 'writable',
    JellyQuestFocus: 'writable',
    JellyQuestHomeScreen: 'writable',
    JellyQuestLibraryScreen: 'writable',
    JellyQuestProfilesScreen: 'writable',
    JellyQuestRequestsBridge: 'writable',
    JellyQuestRequestsScreen: 'writable',
    JellyQuestSearchScreen: 'writable',
    JellyQuestSession: 'writable',
    JellyQuestShell: 'writable',
    // Provided by the host jellyfin-web bundle, not by us.
    ApiClient: 'readonly',
    playbackManager: 'readonly',
    // Provided by the Tizen runtime (absent in the browser simulator).
    tizen: 'readonly',
    webapis: 'readonly',
};

export default [
    {
        ignores: [
            'node_modules/**',
            // Generated by `npm run build:overlay` from src/overlay/** --
            // committed, but never edited by hand, and it embeds the
            // vendored spatial-navigation-polyfill verbatim.
            'jellyquest.js',
            'jellyquest.css',
            // Vendored upstream polyfill: not ours to lint or fix.
            '**/spatial-navigation-polyfill/**',
            // Build output and scratch directories.
            'www/**',
            '.cache/**',
            'artifacts/**',
            '.worktrees/**',
        ],
    },

    // ---- Modern Node ESM (build machine only) ----
    {
        files: ['scripts/**/*.mjs', 'test/**/*.mjs', 'eslint.config.mjs', 'gulpfile.babel.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: globals.node,
        },
        rules: {
            ...js.configs.recommended.rules,
            'no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
        },
    },

    // The Playwright specs drive a real browser: the callbacks handed to
    // page.evaluate()/waitForFunction() are serialised and run inside the
    // page, so they legitimately reference document/window.
    {
        files: ['test/e2e/**/*.mjs'],
        languageOptions: {
            globals: { ...globals.node, ...globals.browser, ...overlayGlobals },
        },
    },

    // ---- ES5 browser code shipped to the TV ----
    {
        files: ['src/overlay/**/*.js', 'tizen.js', 'dev/fixtures/**/*.js'],
        languageOptions: {
            // Hard floor: Tizen 4.6 / Chromium ~M56-M63. Do not raise.
            ecmaVersion: 5,
            sourceType: 'script',
            // ecmaVersion 5 constrains the *syntax* we may write. It does
            // not constrain which runtime builtins exist: Chromium M56
            // has had Promise since M32 and typed arrays since M7, and
            // the overlay uses both. Layering the es2015 globals back in
            // keeps no-undef honest without letting ES6 syntax through.
            globals: { ...globals.es2015, ...globals.browser, ...overlayGlobals },
        },
        rules: {
            ...js.configs.recommended.rules,
            // caughtErrors is off here, and only here: ES5 has no
            // optional catch binding, so `catch (error) { ... }` must
            // name a binding even when the handler deliberately discards
            // the error. Flagging that would report a syntax requirement
            // as a defect. The modern ESM block above still checks it.
            'no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrors: 'none' }],
            // Every overlay file is an IIFE precisely so it adds nothing
            // to the global scope it shares with jellyfin-web; a stray
            // top-level declaration would be a real collision risk.
            'no-implicit-globals': 'error',
        },
    },
];
