// ESLint flat config for JellyQuest.
//
// This repo deliberately contains TWO different JavaScript dialects, and
// the whole point of this file is to keep them apart:
//
//   * src/overlay/**, tizen.js and dev/fixtures/** are hand-written ES5
//     (var, IIFEs, no modules, no arrow functions). The measured hardware
//     floor is Tizen 5.0 / Chromium M63 (2019 UN55RU7100FXZA); the other
//     target is measured Tizen 5.5 / Chromium M69 (2020 UN65TU7000FXZA).
//     See the README's "Target hardware" section for the full matrix.
//     scripts/build-overlay.mjs concatenates these files into a single
//     classic <script>. ecmaVersion 5 is deliberately conservative, not
//     strictly minimal: arrow functions, const and template literals are
//     supported on both sets. Optional catch binding (`try{}catch{}`),
//     however, requires M66: eval('try{}catch{}') measurably throws
//     SyntaxError: Unexpected token { on M63. Parsing on M69 is expected
//     (inferred, not probed), so this would crash on the older TV and is
//     expected to be fine on the newer one.
//     If the ES5 setting is ever relaxed, optional catch binding must
//     remain banned.
//
//   * scripts/**.mjs, test/**.mjs and gulpfile.babel.js are modern Node
//     ESM and only ever run on the build machine, so they get the
//     current ecmaVersion and node globals.
//
// Rule selection is deliberately bug-focused (undefined variables,
// unused variables, unreachable code, accidental globals) rather than
// stylistic -- this gate exists to catch mistakes, not to churn source.
import js from '@eslint/js';
import globals from 'globals';

// Globals the overlay bundle publishes onto `window` and then reads back
// from sibling files. build-overlay.mjs concatenates the files in a
// fixed order, so these really are cross-file globals by design; without
// declaring them here every module would trip no-undef on its siblings.
const overlayGlobals = {
    JellyQuestCards: 'writable',
    JellyQuestDetailScreen: 'writable',
    JellyQuestFocus: 'writable',
    JellyQuestHomeScreen: 'writable',
    JellyQuestLibraryScreen: 'writable',
    JellyQuestProfilesScreen: 'writable',
    JellyQuestRequestsBridge: 'writable',
    JellyQuestRequestsScreen: 'writable',
    JellyQuestSearchScreen: 'writable',
    JellyQuestSession: 'writable',
    JellyQuestShell: 'writable',
    // Provided by the host jellyfin-web bundle, not by us.
    ApiClient: 'readonly',
    playbackManager: 'readonly',
    // Provided by the Tizen runtime (absent in the browser simulator).
    tizen: 'readonly',
    webapis: 'readonly',
};

export default [
    {
        ignores: [
            'node_modules/**',
            // Generated by `npm run build:overlay` from src/overlay/** --
            // committed, but never edited by hand, and it embeds the
            // vendored spatial-navigation-polyfill verbatim.
            'jellyquest.js',
            'jellyquest.css',
            // Vendored upstream polyfill: not ours to lint or fix.
            '**/spatial-navigation-polyfill/**',
            // Build output and scratch directories.
            'www/**',
            '.cache/**',
            'artifacts/**',
            '.buildResult/**',
            '.worktrees/**',
        ],
    },

    // ---- Modern Node ESM (build machine only) ----
    {
        files: ['scripts/**/*.mjs', 'test/**/*.mjs', 'eslint.config.mjs', 'gulpfile.babel.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: globals.node,
        },
        rules: {
            ...js.configs.recommended.rules,
            'no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
        },
    },

    // The Playwright specs drive a real browser: the callbacks handed to
    // page.evaluate()/waitForFunction() are serialised and run inside the
    // page, so they legitimately reference document/window.
    {
        files: ['test/e2e/**/*.mjs'],
        languageOptions: {
            globals: { ...globals.node, ...globals.browser, ...overlayGlobals },
        },
    },

    // ---- ES5 browser code shipped to the TV ----
    {
        files: ['src/overlay/**/*.js', 'tizen.js', 'dev/fixtures/**/*.js'],
        languageOptions: {
            // Conservative syntax policy for the measured Tizen 5.0 / M63
            // floor; see above before considering any relaxation.
            ecmaVersion: 5,
            sourceType: 'script',
            // ecmaVersion 5 constrains the *syntax* we may write. It does
            // not constrain which runtime builtins exist: Chromium M63
            // supports Promise and typed arrays, and the overlay uses
            // both. Layering the es2015 globals back in keeps no-undef
            // honest without letting ES6 syntax through.
            //
            // Known limitation, recorded rather than fixed here: this
            // gate therefore checks SYNTAX only, and cannot tell you that
            // a runtime API is too new for the whole supported range.
            // An API introduced after M63 could parse and lint clean
            // while failing on the older TV. Catching that needs a
            // browser-compat rule set (eslint-plugin-compat or similar),
            // which is out of scope for this gate.
            globals: { ...globals.es2015, ...globals.browser, ...overlayGlobals },
        },
        rules: {
            ...js.configs.recommended.rules,
            // Caught errors ARE checked here, same as in the modern ESM
            // block. ES5 has no optional catch binding, so a handler that
            // deliberately discards its error still has to name one --
            // but that is an exception to argue at each site, not a
            // repo-wide licence, so it is suppressed with a narrow inline
            // disable comment where it genuinely applies. There is exactly
            // one such site today: src/overlay/requests-bridge.js.
            'no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
            // Every overlay file is an IIFE precisely so it adds nothing
            // to the global scope it shares with jellyfin-web; a stray
            // top-level declaration would be a real collision risk.
            'no-implicit-globals': 'error',
        },
    },
];
